version: "3.7"
services:

  postgres:
    image: postgres:13-alpine
    container_name: fantasy-postgres
    environment:
      - POSTGRES_USER=fantasy
      - POSTGRES_PASSWORD=fantasy
      - POSTGRES_DB=fantasy
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: fantasy-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"