---
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/fantasy"
    username: "fantasy"
    password: "fantasy"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

app:
  jwt:
    base64-secret: "5Gd3F99LKe2VfDN0bMNtASeldaw9kH1854XMiTbkd57M0b99clYPcGp7KWDjjE7N8Wu2cItmAjyExEyjtVyBtA=="
    access-token-validity: 3600
    refresh-token-validity: 86400